In [1]:
import random
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
import os
import pickle
import glob
from sklearn.preprocessing import MinMaxScaler

In [2]:
cross_rate = 0.8
mute_rate = 0.15

In [3]:
lnr_model = pickle.load(open('Linear_Model.sav', 'rb'))

In [4]:
data = pd.read_excel("Dataset.xlsx",header=None)
population = data.iloc[:,6:10].values
Y = data.iloc[:,5].values
result = Y.reshape(Y.shape[0],1)

In [5]:
def fitness_function(pop,model):
    
    fitness = abs(model.predict(pop))
    
    return fitness

In [6]:
def boltzmann_selection(alpha,current_gen,total_gen,To,fitness,no_parents,pop):
    
    k=1+100*(current_gen/total_gen)
    parents=np.empty([no_parents,pop.shape[1]])
    T=To*((1-alpha)**k)
    fmax=max(fitness)
    prob_bs=[0]*pop.shape[0]
    
    for i in range(pop.shape[0]):
        prob_bs[i]=math.exp(-(fmax-fitness[i])/T)
    
    cdf=[prob_bs[0]]
    for j in range(1,pop.shape[0]):
        cdf.append(cdf[-1]+prob_bs[i])
        
    for i in range(1,no_parents):
        selected=random.choices(pop,weights=cdf,k=1)
        parents[i]=selected[0]
        
    return parents

In [7]:
def crossover(parent,no_offspring,alpha):

    offspring=np.empty([no_offspring,parent.shape[1]])
    
    for i in range(no_offspring):
        parent1_index=i%parent.shape[0]
        parent2_index=(i+1)%parent.shape[0]
        n=random.random()
    
        if(n<cross_rate):
            #try n-point crossover
            factor = n*parent[parent1_index]+(1-n)*parent[parent2_index]
            if (factor[0]<=160 and factor[0]>=140 and factor[1]<=70 and factor[1]>=60 and factor[2]<=750 and factor[2]>=550 and factor[3]<=20 and factor[3]>=10):
                offspring[i]=factor
            else:
                i-=1
        else:
            offspring[i]=parent[parent1_index]
        
    return offspring

In [8]:
def mutation(offspring):
    
    mutation=np.array(offspring,copy=True)
        
#     for k in range(offspring.shape[0]):
#         m=random.random()
#         if m>mute_rate:
#             continue
            
#         for j in range(offspring.shape[1]):
#             sign=random.randint(0,1)
#             if sign==0:
#                 mutation[k][j]=mutation[k][j]+random.random()
#             else:
#                 mutation[k][j]=mutation[k][j]-random.random()

    
    return mutation

In [9]:
def optimization(pop,no_generation,no_parent):
    
    for m in range(no_generation):

        pop_size=50
        no_offspring=pop_size-no_parent
        fitness=fitness_function(pop,lnr_model)
        parent=boltzmann_selection(0.6,m,no_generation,10,fitness,no_parent,pop)
        offspring=crossover(parent,no_offspring,0.7)
        mutate=mutation(offspring)
        pop=np.concatenate((pop,mutate),axis=0)
        
    return pop,fitness

In [10]:
pop,fitness=optimization(population,10,10)

C:\Users\satwi\AppData\Local\Temp/ipykernel_14652/3037242721.py:10: RuntimeWarning: overflow encountered in true_divide
  prob_bs[i]=math.exp(-(fmax-fitness[i])/T)
C:\Users\satwi\AppData\Local\Temp/ipykernel_14652/3037242721.py:10: RuntimeWarning: overflow encountered in true_divide
  prob_bs[i]=math.exp(-(fmax-fitness[i])/T)
C:\Users\satwi\AppData\Local\Temp/ipykernel_14652/3037242721.py:10: RuntimeWarning: overflow encountered in true_divide
  prob_bs[i]=math.exp(-(fmax-fitness[i])/T)
C:\Users\satwi\AppData\Local\Temp/ipykernel_14652/3037242721.py:10: RuntimeWarning: overflow encountered in true_divide
  prob_bs[i]=math.exp(-(fmax-fitness[i])/T)
C:\Users\satwi\AppData\Local\Temp/ipykernel_14652/3037242721.py:10: RuntimeWarning: overflow encountered in true_divide
  prob_bs[i]=math.exp(-(fmax-fitness[i])/T)
C:\Users\satwi\AppData\Local\Temp/ipykernel_14652/3037242721.py:10: RuntimeWarning: overflow encountered in true_divide
  prob_bs[i]=math.exp(-(fmax-fitness[i])/T)


In [11]:
fitness

array([[1.17962618e+001],
       [1.21400942e+001],
       [1.24839265e+001],
       [1.21584446e+001],
       [1.25022769e+001],
       [1.28461092e+001],
       [1.25206273e+001],
       [1.28644596e+001],
       [1.32082919e+001],
       [1.11404132e+001],
       [1.14842455e+001],
       [1.18280778e+001],
       [1.15025959e+001],
       [1.18464282e+001],
       [1.21902605e+001],
       [1.18647786e+001],
       [1.22086109e+001],
       [1.25524432e+001],
       [1.04845645e+001],
       [1.08283968e+001],
       [1.11722291e+001],
       [1.08467473e+001],
       [1.11905796e+001],
       [1.15344119e+001],
       [1.12089300e+001],
       [1.15527623e+001],
       [1.18965946e+001],
       [1.17690605e+001],
       [1.21128928e+001],
       [1.24567251e+001],
       [1.21312432e+001],
       [1.24750755e+001],
       [1.28189078e+001],
       [1.24934259e+001],
       [1.28372582e+001],
       [1.31810905e+001],
       [1.11132118e+001],
       [1.14570441e+001],
       [1.18

In [12]:
index = np.where(fitness==np.amax(fitness))
index

(array([154], dtype=int64), array([0], dtype=int64))

In [13]:
fitness[index]

array([1.71641987e+293])

In [14]:
pop[index, :]

array([[[4.74807255e+289, 1.30854776e+294, 1.61010085e+251,
         3.48170144e-188]],

       [[1.40000000e+002, 6.00000000e+001, 5.50000000e+002,
         1.00000000e+001]]])